[build]
  functions = "src"
  publish = "dist"

[[redirects]]
  from = "https://testapijib.netlify.app/api/*"
  to = "https://testapijib.netlify.app/.netlify/functions/api/:splat"
  status = 200
  force = true